### ISSUE TITLE
Odd message from PostCSS

### ISSUE THREAD

**Issue by bfkeinberg** [anthonygore/html-critical-webpack-plugin#11]
Has anyone else seen this while running critical? 

Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.

**Comment by thescientist13** [comment]
Hey @bfkeinberg 

Can you see if this is still an issue with the latest release of this plugin?  If the issue still persists, can you please provide more info on what the expected behavior of `from` should be and / or where it's documented so I could review it?

**Comment by bfkeinberg** [comment]
Well, I do still see it, but I haven't yet been able to trace how PostCSS
is used by the plugin. Actually, strike that, a grep seems to indicate that
in the image inlining. But I don't know still where it's invoked from
precisely or how.

**Comment by bfkeinberg** [comment]
Sure, thanks!

This is what I see at the start of my output, iff I use the HtmlCritical plugin:

Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
Hash: f4c88884bbebeeb7bcbd
Version: webpack 4.12.0

My config for the plugin is as follows:

        new HtmlCriticalPlugin({
            base: path.resolve(__dirname, 'dist/'),
            src: 'index.html',
            dest: 'index.html',
            inline: true,
            minify: true,
            extract: false,
            width: 1400,
            height: 1200,
            inlineImages: true,
            assetPaths: ['dist/static'],
            penthouse: {
                renderWaitTime: 3000,
                blockJSRequests: false,
            }

What's puzzled me is where PostCSS comes into this.

**Comment by thescientist13** [comment]
@bfkeinberg 
Gotcha, sorry for taking me a little while to catch on here, I wasn't sure if what you had provided originally was the actual error message itself, or just your description of it.  🙃  Apologies there.

So **critical** [uses **postCSS**](https://github.com/addyosmani/critical/blob/master/package.json#L46) and so that would account for why this might be showing for you.  One of the main options of **PostCSS** is [`from`](https://github.com/postcss/postcss#js-api)
```javascript
const fs = require('fs');
const postcss = require('postcss');
const precss = require('precss');
const autoprefixer = require('autoprefixer');

fs.readFile('src/app.css', (err, css) => {
    postcss([precss, autoprefixer])
        .process(css, { from: 'src/app.css', to: 'dest/app.css' })
        .then(result => {
            fs.writeFile('dest/app.css', result.css, () => true);
            if ( result.map ) {
                fs.writeFile('dest/app.css.map', result.map, () => true);
            }
        });
});
```

Here is an [example](https://github.com/addyosmani/critical/blob/master/lib/core.js#L116) of where it is being used in **critical**, for image inlining it seems?

Maybe if you can share your project and / or the simplest **webpack** configuration that reproduces the issue that I could try out?  It could be an order of operations issue with what order your plugins are being loaded relative to the availability of built assets from **webpack**. 

For reference, [here](https://github.com/ProvidenceGeeks/website-frontend) is a project where I am using **HtmlCriticalWebpackPlugin** and how I am building CSS.    

Likely the root cause is not in this plugin specifically [since it is just a wrapper around **critical**](#25 ) but hopefully we can help point you in the right direction to getting the resolved one way or another, and help to open an upstream issue somewhere if needed!  ✌️

**Comment by bfkeinberg** [comment]
Armed with this info, I experimented with changing 'inlineImages:false' (it had been true) in my webpack config, and that causes the message to go away. So it looks like the PostCSS issue is only when image inlining is turned on.

**Comment by thescientist13** [comment]
@bfkeinberg 
Might be worth look in the **critical** issue tracker for any similar reports?

Another thought is to try calling **critical** from the CLI (or with `node` from a _.js_).  Essentially recreate the config you have in **webpack** and call `critical` manually.

So essentially generate a **webpack** build (WITHOUT **HtmlWebpackCriticalPlugin**) and then call **critical**.  If the issue persists, I would say the issue lies in **critical** itself, and that an issue should be opened there.

**Comment by bfkeinberg** [comment]
You are completely right, I already had a standalone js file to call critical directly, for my own testing, and when I run that, I see the PostCSS warning message above, but only if inlineImages is turned on. It does seem like a bug in critical.

**Comment by thescientist13** [comment]
Glad you were able to get to the bottom of it!  Let us know if you're able to get the issue resolved upstream!
