### ISSUE TITLE
webpack-dev-server not critial css!

### ISSUE THREAD

**Issue by crazychicken** [anthonygore/html-critical-webpack-plugin#28]
I'm try your demo https://github.com/anthonygore/hcwp-demo.
And run with webpack-dev-server:
cross-env NODE_ENV=production webpack-dev-server --open --config webpack.config.js

I don't see html-critical-webpack-plugin works. Can you help me?

**Comment by thescientist13** [comment]
Hey @crazychicken , thanks for reaching out.

To help you out best, we would need more information from you since it's not quite clear to me what issue you are facing.  

Could you please provide
- error you are seeing
- _webpack.config.js_
- version of all relevant tools (webpack, HWCP, etc)
- sample code that reproduces the isssue (is this Angular, React, Vue, etc??)

In my experience, I don't usually extract CSS (MiniCss or EWTP) for development workflows.  When working with **webpack-dev-server**, I usually use `style-loader` at the end of my CSS chain, and also I wouldn't be setting `NODE_ENV=production`.  Not sure if any of those may cause a conflict in your specific workflow.

Hope that helps.

**Comment by crazychicken** [comment]
Hi @thescientist13 
After i clone your project,
I run setup:
```
npm install
npm run build
npm run serve
```
**This is good plugins with ‘http-server’.**

![screen shot 2018-09-04 at 9 49 02 pm](https://user-images.githubusercontent.com/1531508/45039004-c6156100-b08c-11e8-8c11-67b56f2cba19.png)

But when i run with webpack-dev-server, i use 
```
npm install webpack-dev-server --save-dev
```
Change package.json.
![screen shot 2018-09-04 at 9 53 32 pm](https://user-images.githubusercontent.com/1531508/45039248-6b303980-b08d-11e8-8559-6594771a3b33.png)

```
npm run dev
```
![screen shot 2018-09-04 at 9 49 59 pm](https://user-images.githubusercontent.com/1531508/45039300-8d29bc00-b08d-11e8-9d94-ec29b08cbfda.png)


This is my problem, i don’t see critical css include head. You can tell me edit that?

**Comment by thescientist13** [comment]
Thanks for the great feedback @crazychicken , that was super helpful for me 👍 

So yeah, what I can say is I've never tried this plugin while working with **webpack-dev-server**.  I don't know if what you're seeing is expected.

Any thoughts @anthonygore ?

**Comment by anthonygore** [comment]
From memory, this plugin won't work with Webpack dev server and that was an intentional design decision. The reason is that 1) it runs very slow 2) you only need critical CSS in production.

**Comment by thescientist13** [comment]
@anthonygore 's previous comments jogged my memory a bit more as to why currently, from a pure technical perspective, I don't think it will be feasible to use this plugin with HCWP during development.

The key point being around how both critical and webpack-dev-server work
- [Critical works by reading an input file, and generating an output file](https://github.com/anthonygore/html-critical-webpack-plugin#example)
- **webpack-dev-server** work entirely in memory

Because this plugin just "call out" to critical CLI, [there is no "integration" with webpack's dependency graph](#27), and so when using **webpack-dev-server**, and not having output files generated, there would be nothing for critical to read from.
